version: '3.8'

services:
  ffc-pay-submission:
    build:
      context: .
      target: production
    image: ffc-pay-submission
    container_name: ffc-pay-submission
    depends_on: 
      - ffc-pay-dax-azurite
      - ffc-pay-submission-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-submission-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PAYMENTSUBMIT_TOPIC_ADDRESS: ${PAYMENTSUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS: ${PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-submission}${MESSAGE_QUEUE_SUFFIX}
      EVENT_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-ffc-pay-event}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-ffc-pay-events}${MESSAGE_QUEUE_SUFFIX}
      FILESEND_TOPIC_ADDRESS: ${SEND_TOPIC_ADDRESS:-ffc-pay-file-send}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_submission
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-submission-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      BATCH_INTERVAL: 10000
  
  ffc-pay-submission-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_submission
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-pay-dax-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-dax-azurite
