version: '3.8'

services:
  ffc-sfi-payment-submission:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-submission
    container_name: ffc-sfi-payment-submission
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-payment-submission-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
