environment: development
name: ffc-sfi-payment-submission
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payment-submission

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-payment-submission-config-map

containerSecret:
  name: ffc-sfi-payment-submission-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 1
  maxReplicas: 2
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 180Mi
  requestCpu: 120m
  limitMemory: 180Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  paymentSubmitTopicAddress: ffc-sfi-payment-submit
  paymentSubmitSubscriptionAddress: ffc-sfi-payment-submit-submission
  azureStorageAccountName: sfipayments
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  outboundContainer: payment-submission-outbound

postgresService:
  postgresDb: ffc_sfi_payment_submission
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-payment-submission-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
