---
environment: production
environmentCode: dev
container:
  messageQueueHost: DEVFFCINFSB1001.servicebus.windows.net
  paymentSubmitTopicAddress: ffc-pay-submit-dev
  paymentSubmitSubscriptionAddress: ffc-pay-submission
  fileSendTopicAddress: ffc-pay-file-send-dev
  eventsTopicAddress: ffc-pay-events-dev
  azureStorageAccountName: devffcpayst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: dax
  storageFolder: outbound
secretProviderClass:
  azure:
    keyvaultName: DEVFFCINFKV1001
    objects:
      - objectName: devtest-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-submission
      type: Opaque
      data:
        - objectName: devtest-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
