---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  processingActive: true
  useV2ReturnFiles: true
  paymentSubmitTopicAddress: ffc-pay-submit
  paymentSubmitSubscriptionAddress: ffc-pay-submission
  fileSendTopicAddress: ffc-pay-file-send
  eventsTopicAddress: ffc-pay-events
  azureStorageAccountName: prdffcpayst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: dax
  storageFolder: outbound
  batchGenerationInterval: 1800000
  batchSize: 2000
  batchCap: 1
postgresService:
  postgresDb: ffc-pay-submission-prd
  postgresqlHost: prdffcdbssq1001.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: prd-postrgresPaySubmissionUser
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-submission
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-postrgresPaySubmissionUser
          key: POSTGRES_USERNAME