---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  paymentSubmitTopicAddress: ffc-pay-submit-prd
  paymentSubmitSubscriptionAddress: ffc-pay-submission
  fileSendTopicAddress: ffc-pay-file-send-prd
  eventsTopicAddress: ffc-pay-events-prd
  azureStorageAccountName: prdffcpayst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: dax
  storageFolder: outbound
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-submission
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
